
// ---------------------------------------------------------------------------------------------------------------------
// jsstrings_en.js
// Copyright (c) 2011 Tableau Software, Incorporated and its licensors. All rights reserved.
// Protected by U.S. Patent 7,089,266; Patents Pending.
// 
// Portions of the code
// Copyright (c) 2002 The Board of Trustees of the Leland Stanford Junior University. All rights reserved.
// ---------------------------------------------------------------------------------------------------------------------

(function(w) {
  var s = {
    AuthAutoRecoveredSessionMessage: "Previous edits have been auto-recovered. Use Revert to return to the workbook as saved.",
    AuthCardCollapsedTitle: "{0} &middot; {1}",
    AuthCardTitleColumns: "Columns",
    AuthCardTitleFilters: "Filters",
    AuthCardTitleMarks: "Marks",
    AuthCardTitleMeasureValues: "Measure Values",
    AuthCardTitlePages: "Pages",
    AuthCardTitleRows: "Rows",
    AuthMarksCardChooseField: "Choose Field…",
    AuthMarksCardEncodingTooltipBasic: "Drag dimensions or measures here.",
    AuthMarksCardEncodingTooltipOptions: "Drag dimensions or measures here, or click for more options.",
    AuthMastheadDone: "Done",
    AuthMastheadDone_Confirm_CanLogin: "Do you want to save your changes to the workbook? <br><br>You will need to sign in before you can finish saving your changes.",
    AuthMastheadDone_Confirm_CanLogin_Confirm: "Sign In and Save",
    AuthMastheadDone_Confirm_CanLogin_Deny: "Don\'t Save",
    AuthMastheadDone_Confirm_CanSave: "Do you want to save your changes to the workbook?",
    AuthMastheadDone_Confirm_CanSaveAs: "Do you want to save your changes in a new workbook?",
    AuthMastheadDone_Confirm_CanSaveAs_Confirm: "Save a Copy",
    AuthMastheadDone_Confirm_CanSaveAs_Deny: "Don\'t Save",
    AuthMastheadDone_Confirm_CanSave_Confirm: "Save",
    AuthMastheadDone_Confirm_CanSave_Deny: "Don\'t Save",
    AuthMastheadDone_Confirm_Title: "Save Workbook",
    AuthMastheadHelp: "Help",
    AuthMastheadLogin: "Login",
    AuthMastheadLogout: "Logout",
    AuthMastheadRevert: "Revert",
    AuthMastheadSave: "Save",
    AuthMastheadSaveAs: "Save As",
    AuthMastheadUserPrefs: "User Preferences",
    AuthPillRemove: "Remove",
    AuthRenameSheet: "Rename Sheet {0}",
    AuthResetTooltip: "Reset Tooltip",
    AuthSaveButtonCancel: "Cancel",
    AuthSaveButtonSave: "Save",
    AuthSaveConfirmOverwrite: "{0} Overwrite it?",
    AuthSaveErrorTitle: "Error Saving",
    AuthSaveLabelEmbedPassword: "Embed data source login information",
    AuthSaveLabelName: "Name:",
    AuthSaveLabelProject: "Project:",
    AuthSaveLabelShowTabs: "Show sheets as tabs",
    AuthSaveTitle: "Save Workbook",
    AuthSaveWorkbookSavedMessage: "Workbook saved",
    AuthSchemaViewerHeaderData: "Data",
    AuthSchemaViewerHeaderDimensions: "Dimensions",
    AuthSchemaViewerHeaderMeaures: "Measures",
    AuthSchemaViewerHeaderParameters: "Parameters",
    AuthSchemaViewerHeaderSets: "Sets",
    AuthShowMeApply: "Apply",
    AuthShowMeCantApply: "Can\'t Apply",
    AuthTabMenuClear: "Clear Worksheet",
    AuthTabMenuDelete: "Delete",
    AuthTabMenuDuplicate: "Duplicate",
    AuthTabMenuNew: "New",
    AuthTabMenuRename: "Rename",
    AuthToolbarAddAllSubtotals: "Add All Subtotals",
    AuthToolbarCellSize: "Cell Size",
    AuthToolbarCellSizeBigger: "Bigger",
    AuthToolbarCellSizeNarrower: "Narrower",
    AuthToolbarCellSizeShorter: "Shorter",
    AuthToolbarCellSizeSmaller: "Smaller",
    AuthToolbarCellSizeTaller: "Taller",
    AuthToolbarCellSizeWider: "Wider",
    AuthToolbarCellTypeSquare: "Square",
    AuthToolbarCellTypeText: "Text",
    AuthToolbarExport: "Export",
    AuthToolbarFont: "Font",
    AuthToolbarFontDecrease: "Decrease Font Size",
    AuthToolbarFontIncrease: "Increase Font Size",
    AuthToolbarRedo: "Redo",
    AuthToolbarRemoveAllSubtotals: "Remove All Subtotals",
    AuthToolbarShare: "Share",
    AuthToolbarShowColumnGrandTotals: "Show Row Grand Totals",
    AuthToolbarShowMe: "Show Me",
    AuthToolbarShowRowGrandTotals: "Show Column Grand Totals",
    AuthToolbarSubscribe: "Subscribe",
    AuthToolbarSwap: "Swap",
    AuthToolbarTotals: "Totals",
    AuthToolbarUndo: "Undo",
    AuthToolbarUpdatesOff: "Updates Off",
    AuthToolbarUpdatesOn: "Updates On",
    AuthorBylineText: "See more vizzes from this author",
    BaseClientAllAxisRanges: "All Axis Ranges",
    BaseClientAllChanges: "All Changes",
    BaseClientAllFilters: "All Filters",
    BaseClientAllSorts: "All Sorts",
    BaseClientColumns: "Columns",
    BaseClientInvalidSheet: "Unable to display view for the sheet \'{0}\'. The sheet is invalid.",
    BaseClientRows: "Rows",
    BaseClientSessionExpiredDialogMessage: "Your viewer session has expired. You must refresh your browser.",
    BaseClientSessionExpiredDialogTitle: "Session Expired",
    BrowserErrorProcessing: "Browser Processing Error",
    BrowserErrorProcessingMessage: "An error occurred processing the server response.",
    ClearAllButtonText: "Clear List",
    ConfirmationButtonConfirm: "Yes",
    ConfirmationButtonDeny: "No",
    ConfirmationTitle: "Confirm",
    CurrentPagePanelShowHistory: "Show History",
    CustomViewsAddYourOwnCustomView: "Add your own custom view",
    CustomViewsCancel: "Cancel",
    CustomViewsCannotChangeDefault: "Cannot change default to an unlisted custom view",
    CustomViewsChangeDefaultTo: "Change default to \"{0}\"",
    CustomViewsCurrentDefaultIs: "Current default is \"{0}\"",
    CustomViewsDefault: "Default",
    CustomViewsDone: "Done",
    CustomViewsManageCustomViews: "Manage Custom Views",
    CustomViewsManageHeader: "Advertise, rename, and delete my custom views",
    CustomViewsMyCustomViews: "My Custom Views",
    CustomViewsNameYourCustomView: "Name your custom view",
    CustomViewsOriginalName: "Original Name: \"{0}\"",
    CustomViewsOriginalView: "Original View",
    CustomViewsOtherCustomViews: "Other Custom Views",
    CustomViewsRemember: "Remember",
    CustomViewsRememberMyChanges: "Remember my changes",
    CustomViewsSelectCustomView: "Select Custom View",
    CustomViewsStartManage: "Manage Custom Views",
    CustomViewsUndo: "Undo",
    CustomViewsUnlistedCustomView: "Unlisted Custom View",
    DialogButtonCancel: "Cancel",
    DialogButtonDownload: "Download",
    DialogButtonExport: "Export",
    DialogButtonOK: "OK",
    DialogNoButtonText: "No",
    DialogYesButtonText: "Yes",
    ExportCrosstabDialogMessage: "The crosstab has been generated.",
    ExportCrosstabDialogTitle: "Export Crosstab",
    ExportDataDialogMessage: "The data has been generated.",
    ExportDataDialogTitle: "Export Data",
    ExportImageDialogMessage: "The image has been generated.",
    ExportImageDialogTitle: "Export Image",
    GlassPaneLoading: "Loading...",
    GlassPaneSessionExpired: "Session Expired",
    GlassPaneUpdating: "Updating...",
    HelpMenuItemAllHelpTopics: "Open Installed Help",
    HelpMenuItemContactSupport: "Contact Support",
    HelpMenuItemGetHelpAndSupport: "Get Help & Support",
    HelpMenuItemOpenInstalledHelp: "Open Installed Help",
    HelpMenuItemWebAuthor1: "Who can edit and create workbooks",
    HelpMenuItemWebAuthor2: "Edit workbooks",
    HelpMenuItemWebAuthor3: "Build a view",
    LegendPanelHighlightSelectedItems: "Highlight Selected Items",
    LogOnTitle: "Login",
    MenuBackButton: "Back",
    MobileClientTapToInteract: "Tap to interact",
    PdfDialogContentDashboard: "This Dashboard",
    PdfDialogContentDashboardSheets: "Sheets in Dashboard",
    PdfDialogContentTopSheets: "Sheets in Workbook",
    PdfDialogContentWorksheet: "This Sheet",
    PdfDialogImageSize: "Image Size (px)",
    PdfDialogPaperSize: "Paper Size",
    PdfDialogScalingLabel: "Scaling",
    PdfDialogSectionContent: "Content",
    PdfDialogSectionLayout: "Layout",
    PdfDialogSelectSheetToChangePrintScaling: "Sheets to Export",
    PdfDialogThumbnailPageSizeLabel: "Page Size",
    PdfDialogThumbnailScalingLabel: "Scale:",
    PdfExportFitHigh: "At most {0} high",
    PdfExportFitOneHigh: "At most 1 page high",
    PdfExportFitOneWide: "At most 1 page wide",
    PdfExportFitTwoHigh: "At most 2 pages high",
    PdfExportFitTwoWide: "At most 2 pages wide",
    PdfExportFitWide: "At most {0} wide",
    PdfExportFitWideByHigh: "At most {0}x{1}",
    PdfExportMessageError: "Error producing PDF!",
    PdfExportMessageErrorPng: "Error exporting PNG",
    PdfExportMessageExporting: "Exporting...",
    PdfExportMessageSettings: "Getting PDF settings from server.",
    PdfExportMessageSettingsError: "Error: Could not retrieve PDF settings from server.",
    PdfExportPageOrientationLandscape: "Landscape",
    PdfExportPageOrientationPortrait: "Portrait",
    PdfExportPageOrientationPrinter: "Printer",
    PdfExportPageScaleAuto: "Automatic",
    PdfExportPageScalePercent: "{0}%",
    PdfExportPageSizeA3: "A3",
    PdfExportPageSizeA4: "A4",
    PdfExportPageSizeA5: "A5",
    PdfExportPageSizeB4: "B4",
    PdfExportPageSizeB5: "B5",
    PdfExportPageSizeExecutive: "Executive",
    PdfExportPageSizeFolio: "Folio",
    PdfExportPageSizeLedger: "Ledger",
    PdfExportPageSizeLegal: "Legal",
    PdfExportPageSizeLetter: "Letter",
    PdfExportPageSizeNote: "Note",
    PdfExportPageSizeQuarto: "Quarto",
    PdfExportPageSizeStatement: "Statement",
    PdfExportPageSizeTabloid: "Tabloid",
    PdfExportPageSizeUnspecified: "Unspecified",
    PdfExportTitlePDF: "Export PDF",
    PdfExportTitlePNG: "Export PNG",
    PressBackButtonMessage: "Use the back button to return to a valid view.",
    PrintPdfDialogContentRequired: "Select at least one sheet to export.",
    PrintPdfDialogMessage: "The PDF file has been generated.",
    PrintPdfDialogTitle: "Export PDF",
    QuickFilterAll: "(All)",
    QuickFilterAllValues: "All Values",
    QuickFilterConditionalsCondition: "Condition",
    QuickFilterConditionalsLimit: "Limit",
    QuickFilterDomainShowFewerValues: "Show Fewer Values",
    QuickFilterDomainShowMoreValues: "Show More Values",
    QuickFilterExclusive: "Exclusive",
    QuickFilterInclusive: "Inclusive",
    QuickFilterMultiSelect: "Multiple",
    QuickFilterMultipleValues: "(Multiple values)",
    QuickFilterNonNullValues: "Non-Null Values",
    QuickFilterOnlyNullValues: "Only Null Values",
    QuickFilterSearch: "Search",
    QuickFilterSearchAddItemCtrlEnter: "Add Item (Ctrl+Enter)",
    QuickFilterSearchAddItemEnter: "Add Item (Enter)",
    QuickFilterSearchCancel: "Cancel Search",
    QuickFilterSearchClearTooltip: "Clear (Esc)",
    QuickFilterSearchCloseTooltip: "Close (Esc)",
    QuickFilterSearchDataIsCaseSensitive: "Data is case sensitive.",
    QuickFilterSearchInvalidDataMemberSingular: "\"{0}\" is not a valid member of the filter.",
    QuickFilterSearchInvalidDataMembersDialogTitle: "Invalid Data Members",
    QuickFilterSearchInvalidDataMembersPlural: "The following values are not valid members of the filter:",
    QuickFilterSearchNoMatches: "No matches.",
    QuickFilterSearchResultsNotShownPlural: "{0} results not shown",
    QuickFilterSearchResultsNotShownSingular: "1 result not shown",
    QuickFilterSearchResultsNotShownZero: "0 results not shown",
    QuickFilterSearchTooltip: "Search (Enter)",
    QuickFilterShowLargerRange: "Show Larger Range",
    QuickFilterShowSmallerRange: "Show Smaller Range",
    QuickFilterSingleSelect: "Single",
    QuickFilterTitleBarExclusive: "{0} (Exclusive)",
    QuickFilterUnknown: "<unknown>",
    QuickFilterValuesInRange: "Values in Range",
    QuickFilterValuesInRangeOrNull: "Values in Range or Null",
    RelDateAnchored_curr_day: "Anchor day",
    RelDateAnchored_curr_hour: "Anchor hour",
    RelDateAnchored_curr_minute: "Anchor minute",
    RelDateAnchored_curr_month: "Anchor month",
    RelDateAnchored_curr_quarter: "Anchor quarter",
    RelDateAnchored_curr_second: "Anchor second",
    RelDateAnchored_curr_week: "Anchor week",
    RelDateAnchored_curr_year: "Anchor year",
    RelDateAnchored_last_day: "Yesterday",
    RelDateAnchored_last_hour: "Previous hour",
    RelDateAnchored_last_minute: "Previous minute",
    RelDateAnchored_last_month: "Previous month",
    RelDateAnchored_last_quarter: "Previous quarter",
    RelDateAnchored_last_second: "Previous second",
    RelDateAnchored_last_week: "Previous week",
    RelDateAnchored_last_year: "Previous year",
    RelDateAnchored_lastn_day: "Last % days",
    RelDateAnchored_lastn_hour: "Last % hours",
    RelDateAnchored_lastn_minute: "Last % minutes",
    RelDateAnchored_lastn_month: "Last % months",
    RelDateAnchored_lastn_quarter: "Last % quarters",
    RelDateAnchored_lastn_second: "Last % seconds",
    RelDateAnchored_lastn_week: "Last % weeks",
    RelDateAnchored_lastn_year: "Last % years",
    RelDateAnchored_next_day: "Tomorrow",
    RelDateAnchored_next_hour: "Next hour",
    RelDateAnchored_next_minute: "Next minute",
    RelDateAnchored_next_month: "Next month",
    RelDateAnchored_next_quarter: "Next quarter",
    RelDateAnchored_next_second: "Next second",
    RelDateAnchored_next_week: "Next week",
    RelDateAnchored_next_year: "Next year",
    RelDateAnchored_nextn_day: "Next % days",
    RelDateAnchored_nextn_hour: "Next % hours",
    RelDateAnchored_nextn_minute: "Next % minutes",
    RelDateAnchored_nextn_month: "Next % months",
    RelDateAnchored_nextn_quarter: "Next % quarters",
    RelDateAnchored_nextn_second: "Next % seconds",
    RelDateAnchored_nextn_week: "Next % weeks",
    RelDateAnchored_nextn_year: "Next % years",
    RelDateAnchored_todate_day: "Day to anchor",
    RelDateAnchored_todate_hour: "Hour to anchor",
    RelDateAnchored_todate_minute: "Minute to anchor",
    RelDateAnchored_todate_month: "Month to anchor",
    RelDateAnchored_todate_quarter: "Quarter to anchor",
    RelDateAnchored_todate_second: "Second to anchor",
    RelDateAnchored_todate_week: "Week to anchor",
    RelDateAnchored_todate_year: "Year to anchor",
    RelDateFilterDays: "Days",
    RelDateFilterHours: "Hours",
    RelDateFilterMinutes: "Minutes",
    RelDateFilterMonths: "Months",
    RelDateFilterPreview: "{0} to {1}",
    RelDateFilterQuarters: "Quarters",
    RelDateFilterWeeks: "Weeks",
    RelDateFilterYears: "Years",
    RelDatePickerFiveYears: "5 years",
    RelDatePickerFiveYearsAbbrev: "5y",
    RelDatePickerOneDay: "1 day",
    RelDatePickerOneDayAbbrev: "1d",
    RelDatePickerOneMonth: "1 month",
    RelDatePickerOneMonthAbbrev: "1m",
    RelDatePickerOneWeek: "1 week",
    RelDatePickerOneWeekAbbrev: "1w",
    RelDatePickerOneYear: "1 year",
    RelDatePickerOneYearAbbrev: "1y",
    RelDatePickerThreeMonths: "3 months",
    RelDatePickerThreeMonthsAbbrev: "3m",
    RelDate_curr_day: "Today",
    RelDate_curr_hour: "This hour",
    RelDate_curr_minute: "This minute",
    RelDate_curr_month: "This month",
    RelDate_curr_quarter: "This quarter",
    RelDate_curr_second: "This second",
    RelDate_curr_week: "This week",
    RelDate_curr_year: "This year",
    RelDate_last_day: "Yesterday",
    RelDate_last_hour: "Previous hour",
    RelDate_last_minute: "Previous minute",
    RelDate_last_month: "Previous month",
    RelDate_last_quarter: "Previous quarter",
    RelDate_last_second: "Previous second",
    RelDate_last_week: "Previous week",
    RelDate_last_year: "Previous year",
    RelDate_lastn_day: "Last % days",
    RelDate_lastn_hour: "Last % hours",
    RelDate_lastn_minute: "Last % minutes",
    RelDate_lastn_month: "Last % months",
    RelDate_lastn_quarter: "Last % quarters",
    RelDate_lastn_second: "Last % seconds",
    RelDate_lastn_week: "Last % weeks",
    RelDate_lastn_year: "Last % years",
    RelDate_next_day: "Tomorrow",
    RelDate_next_hour: "Next hour",
    RelDate_next_minute: "Next minute",
    RelDate_next_month: "Next month",
    RelDate_next_quarter: "Next quarter",
    RelDate_next_second: "Next second",
    RelDate_next_week: "Next week",
    RelDate_next_year: "Next year",
    RelDate_nextn_day: "Next % days",
    RelDate_nextn_hour: "Next % hours",
    RelDate_nextn_minute: "Next % minutes",
    RelDate_nextn_month: "Next % months",
    RelDate_nextn_quarter: "Next % quarters",
    RelDate_nextn_second: "Next % seconds",
    RelDate_nextn_week: "Next % weeks",
    RelDate_nextn_year: "Next % years",
    RelDate_todate_day: "Day to date",
    RelDate_todate_hour: "Hour to date",
    RelDate_todate_minute: "Minute to date",
    RelDate_todate_month: "Month to date",
    RelDate_todate_quarter: "Quarter to date",
    RelDate_todate_second: "Second to date",
    RelDate_todate_week: "Week to date",
    RelDate_todate_year: "Year to date",
    RequestAbortedByBrowser: "Request Aborted by Browser",
    SaveIncompleteWorkbookWarning: "Not all views were shared when this workbook was published. Saving the workbook will overwrite the original workbook, and the unshared views will be lost. Consider using Save As instead.",
    ServerErrorGeneral: "An error occurred communicating with the server ({0}).<br>This may be a temporary network condition.  Please retry the operation.<br>If this condition persists, contact your system administrator.",
    ServerErrorInvalidJSON: "An error occurred communicating with the server (Invalid JSON).",
    ServerErrorRejected: "Request Rejected by Server",
    ServerErrorRejectedMessage: "The server could not respond due to a malformed request.<br>This may be a temporary network condition.  Please retry the operation.<br>If this condition persists, contact your system administrator.",
    ServerErrorTitle: "Server Error",
    ServerErrorUnexpected: "Unexpected Server Error",
    SessionEndedAlertMessage: "Would you like to reset the view?",
    SessionEndedAlertTitle: "Session Ended by Server",
    SessionForbiddenActionMsg: "You are not authorized to perform this action.",
    SessionForbiddenActionTitle: "Forbidden Action",
    SessionUnknownErrorTitle: "Unknown Server Error",
    ShareDialogAndroidLinkText: "Tap icon to open link",
    ShareDialogDisplayOptions: "Display Options",
    ShareDialogDoneButton: "Done",
    ShareDialogEmail: "Email:",
    ShareDialogEmailHelp: "Copy and Paste link into your email message",
    ShareDialogEmbed: "Embed:",
    ShareDialogEmbedCodeTableauText: "Learn About Tableau",
    ShareDialogEmbedHelp: "Copy and Paste HTML code to embed the view in your website",
    ShareDialogEnterUriForBlogEntry: "Enter the URI for the blog entry",
    ShareDialogEnterValueBetween: "Enter a value between {0} and {1}",
    ShareDialogHeight: "Height:",
    ShareDialogInvalidHeight: "Invalid height.",
    ShareDialogInvalidWidth: "Invalid width.",
    ShareDialogLink: "Link:",
    ShareDialogMobileEmailText: "Tap icon to send the link by email",
    ShareDialogMobileLinkText: "Tap and hold icon to access other sharing options",
    ShareDialogPleaseEnterIntegerBetween: "Please enter an integer between {0} and {1}",
    ShareDialogShowTabs: "Show Tabs",
    ShareDialogShowToolbar: "Show Toolbar",
    ShareDialogTitle: "Share View",
    ShareDialogUrlForRssLinks: "URL for RSS links:",
    ShareDialogWaitingEmbedMessage: "creating your custom embed code ...",
    ShareDialogWaitingLinkMessage: "creating your custom link ...",
    ShareDialogWidth: "Width:",
    SizeLegendTextMarkSwatch: "Abc",
    SpecialAll: "All",
    SpecialError: "#Error",
    SpecialManyValues: "*",
    SpecialMissing: "#Missing",
    SpecialNoAccess: "#NoAccess",
    SpecialRagged: "#Ragged",
    SpecialSkipped: "#Skipped",
    SpecialWildcard: "Wildcard",
    SubscribeButtonTooltip: "Subscribe",
    SubscribeCancel: "Cancel",
    SubscribeContent: "Content:",
    SubscribeEnterAddress: "To receive subscriptions enter your email address.",
    SubscribeFailure: "Subscription failed.",
    SubscribeInvalidAddress: "Please enter a valid email address. ",
    SubscribeNext: "Next",
    SubscribeSchedule: "Schedule:",
    SubscribeSheet: "This Sheet",
    SubscribeSubject: "Subject:",
    SubscribeSubscribe: "Subscribe",
    SubscribeSuccess: "Subscription successfully saved.",
    SubscribeTitle: "Subscribe",
    SubscribeTo: "To:",
    SubscribeWorkbook: "Sheets in Workbook",
    SumOf: "SUM of",
    TimeLimitExceededTitle: "Session Time Limit Exceeded",
    TimeLimitExceededWarning: "Computing the current visualization has exceeded the session time limit.",
    ToolbarDownload: "Download",
    ToolbarEdit: "Edit",
    ToolbarExport: "Export",
    ToolbarExportCrosstab: "Crosstab",
    ToolbarExportData: "Data",
    ToolbarExportImage: "Image",
    ToolbarPauseAutomaticUpdates: "Pause Automatic Updates",
    ToolbarPrintToPdf: "PDF",
    ToolbarRefreshData: "Refresh data for this view",
    ToolbarResumeAutomaticUpdates: "Resume Automatic Updates",
    ToolbarRevertAll: "Revert All",
    ToolbarSetCurrentPage: "Set the current page",
    ToolbarShare: "Share",
    ToolbarShowPerformanceRecording: "Show performance recording",
    ToolbarToggleAutoUpdate: "Toggle Auto Update",
    TooltipPanZoomMessage: "Double-click to zoom / Press-and-hold to pan",
    UbertipClearSelection: "Clear<br/>Selection",
    UbertipCommand1Mobile: "Clear<br/>Selection",
    UbertipCommand7Mobile: "View Data",
    UbertipDrillDownMobile: "Drill Down",
    UbertipDrillUpMobile: "Drill Up",
    UbertipExcludeMobile: "Exclude",
    UbertipItemsSelected: "items selected",
    UbertipKeepOnlyMobile: "Keep Only",
    UbertipMergeMobile: "Group Members",
    UbertipSortAscendingMobile: "Sort Ascending",
    UbertipSortDescendingMobile: "Sort Descending",
    UbertipSplitMobile: "Ungroup Members",
    UbertipViewData: "View Data"
};

  if (!window.tab) { Type.registerNamespace('tab'); }
  if (!tab.Strings) {
    tab.Strings = {
      noLoc: function(str) { return str; },
      getString: function(strKey) { return typeof (tab.Strings[strKey]) === 'undefined' ? '!' + strKey + '!': tab.Strings[strKey]; }
    };
    for (var key in s) {
      if (s.hasOwnProperty(key)) {
        tab.Strings[key] = function() {
          var k = key, hasParams = /{[^}{]+}/.test(s[k]);
          return hasParams ?
            function() {
              var formattedString = s[k], placeHolder, i, len;
              for (i = 0, len = arguments.length; i < len; i++) {
                placeHolder = "{" + i + "}";
                formattedString = formattedString.replace(placeHolder, arguments[i]); 
              }
              return formattedString;
            } :
            s[k];
        }();
      }
    }
  }
}(window));


